[package]
name = "mcap-extractor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
mcap = { version = "0.9.1", features = ["zstd"] }
memmap = "0.7.0"
ros2_message = "0.0.5"
zstd = "0.13.2"
